version: '2.4'

services:
  express:
    build: .
    # to override if uncommented
    # # for development in Linux
    # command: nodemon ./bin/www
    # # for development in Windows
    command: nodemon -L ./bin/www
    ports:
      - 80:3000
    volumes:
      - ./src:/app
    environment:
      - NODE_ENV=development

