## docker-compose.yml
version: '2'

# same as 
# docker container run -d --name nginx-in-compose -p 8080:80 -v ${pwd}:/usr/share/nginx/html nginx

services:
  nginx-in-compose:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - '8080:80'

