version: '2.4'

services:
  web:
    init: true
    build: 
      context: .
      target: dev
    ports:
      - "80:3000"
    volumes:
      - ./src:/opt/app:delegated
      - /opt/app/node_modules

